### PR TITLE
add login and logout into app

### PR DESCRIPTION
**Pull request by chileap**
This add login and logout into app but not yet with the style.

### CODE REVIEW

**Comment by chileap** [comment]
Ok I will remove this. sorry for that

**Comment by chileap** [comment]
@michaelbina I have updated the code. please kindly to review it

**Comment by michaelbina** [comment]
I'm getting this error @chileap 

> Failed to compile
> ./src/components/Auth/react-auth-spa.js
>   Line 84:  'client' is not defined  no-undef
> 
> Search for the keywords to learn more about each error.

**Comment by chileap** [comment]
I have updated it and fixed already

**Comment by michaelbina** [comment]
Screen Shot 2020-04-25 at 8 26 19 AM

Now I see this error when I try to log out.

**Comment by chileap** [comment]
Hi @michaelbina I have fixed and refactor the cache of logined user too. Please kindly to check it and don't forget to pull from reshare web with branch ` add-auth-to-grapql` since I just updated it with sign out too.

**Pull request merged**
